profiles:
- domain_pattern: princeton\.edu
  name: Princeton University
  faculty_urls:
  - https://www.princeton.edu/meet-princeton/people
  - https://www.cs.princeton.edu/people/faculty
  - https://ece.princeton.edu/people/faculty
  - https://mae.princeton.edu/people/faculty
  - https://cs.princeton.edu/people/faculty
  selectors:
    container: .people-list, .faculty-list, .views-row
    name: .field-name-title a, h3 a, .people-name
    title: .field-name-field-title, .position, .people-title
    email: a[href^='mailto:']
    profile_link: .field-name-title a, h3 a
  pagination:
    type: click
    max_pages: 10
- domain_pattern: mit\.edu
  name: Massachusetts Institute of Technology
  faculty_urls:
  - https://www.eecs.mit.edu/people/faculty-advisors
  - https://meche.mit.edu/people
  selectors:
    container: .person-card, .profile-item
    name: .card-title, .name
    title: .card-subtitle, .title
  pagination:
    type: infinite_scroll
    scroll_pause: 2.0
- domain_pattern: stanford\.edu
  name: Stanford University
  faculty_urls:
  - https://profiles.stanford.edu/browse/all
  selectors:
    container: .profile-item
  pagination:
    type: alpha
- domain_pattern: iit[a-z]+\.ac\.in
  name: Indian Institute of Technology
  discovery_hints:
  - /people/
  - /faculty/
  - faclistbydepartment
  selectors:
    container: .card, .faculty-card, .profile-card, .person-card
    name: .card-title, .name, h3, h4
    title: .card-subtitle, .title, .position
    email: a[href^='mailto:']
    profile_link: a.card-link, .card-title a, h3 a
  pagination:
    type: datatable
    items_per_page: 25
  faculty_urls:
  - https://www.cse.iitb.ac.in/people/faculty
- domain_pattern: .*\.edu$
  name: Generic US University
  discovery_hints:
  - /people/
  - /faculty/
  - /directory/
  selectors: null
  pagination: null
